Site\FirstBundle\Entity\StaticPage:
    type: entity
    table: staticPage
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        slug:
            type: string
            length: 255
        title:
            type: string
            length: 255
        content:
            type: text
    lifecycleCallbacks: {  }
