bundles_user_instagram_auth:
    path:     /instagram_auth
    defaults: { _controller: BundlesUserBundle:Instagram:authLogin }

bundles_user_facebook_auth:
    path:     /facebook_auth
    defaults: { _controller: BundlesUserBundle:Facebook:authLogin }
    
bundles_user_user_profile:
    path:     /user_profile
    defaults: { _controller: BundlesUserBundle:UserProfile:showProfile }


    
bundles_user_edit_profile:
    path:     /edit_profile
    defaults: { _controller: BundlesUserBundle:UserProfile:profile }